services:
  - type: web
    name: primesec-autobot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: ACCESS_TOKEN
        value: EAAN8FmSzGREBPI4wXrAdmTQScYzdbZCZCZARTE6ZAYh7KpKilZA6dU5qKNX8ALQbsRAsfDkzbhRPiKz93LV5bFIxiNJyb9Jr72HwBH84G99HqwqZBYyMQhT3mZCegCiRjtozY95p0KV5gQjwW76GVdUQxo2rhShrNEALcN7eDKLJjZANnLZCQeXgH1mgq3VLT5zRdH125hN3ir6hqElv5fez6cdjKW7Jwetc2gutJFdgZD
      - key: VERIFY_TOKEN
        value: primesecverifytoken
      - key: PAGE_ID
        value: 673961842474688
      - key: IG_ID
        value: 17841475275756978
